<?xml version="1.0"?>
<package format="2">
  <name>morai_bringup</name>
  <version>0.1.0</version>
  <description>Composition launch files for the 2026 MORAI competition stack.</description>

  <maintainer email="stier@todo.todo">STIER</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>ioniq5_description</exec_depend>
  <exec_depend>morai_localization</exec_depend>
  <exec_depend>morai_path_manager</exec_depend>
  <exec_depend>morai_udp_bridge</exec_depend>
  <exec_depend>morai_visualization</exec_depend>
  <exec_depend>nodelet</exec_depend>
  <exec_depend>velodyne_driver</exec_depend>
  <exec_depend>velodyne_laserscan</exec_depend>
  <exec_depend>velodyne_pointcloud</exec_depend>

  <test_depend>python3-nose</test_depend>

  <export/>
</package>
