joy_node:
  dev: /dev/input/by-id/usb-ShanWan_Xbox360_For_Windows_10F36D6-joystick
  deadzone: 0.05
  autorepeat_rate: 20.0
  coalesce_interval: 0.001
  default_trig_val: true

joystick_teleop_node:
  joy_topic: /joy
  command_topic: /vehicle/manual_command
  steering_axis: 0
  brake_axis: 2
  accel_axis: 5
  steering_inverted: false
  brake_inverted: true
  accel_inverted: true
  steering_deadzone: 0.05
  odometry_topic: /localization/odometry
  odometry_timeout: 0.5
  maximum_gear_change_speed_mps: 0.5
  initial_gear: 4
  drive_button: 0
  neutral_button: 1
  reverse_button: 2
  park_button: 3

morai_udp_sender_node:
  command_topic: /vehicle/manual_command
  destination_ip: 127.0.0.1
  destination_port: 9093
  send_rate: 50.0
  command_timeout: 0.25
  safe_brake: 0.5
